apiVersion: v1
kind: Service
metadata:
  name: svc-frontendapp
  labels:
    app: frontendapp
    env: pro
    partition: bgstone
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontendapp
  sessionAffinity: None
  type: ClusterIP